@startuml ERD FinCloud
!theme plain
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam defaultFontSize 11
skinparam class {
  BackgroundColor #DAE8FC
  BorderColor #1F4E79
  ArrowColor #1F4E79
  HeaderBackgroundColor #1F4E79
  HeaderFontColor #FFFFFF
}

' ============ ENTITIES ============

entity "roles" as roles {
  *id : SERIAL <<PK>>
  --
  name : VARCHAR(20) <<UNIQUE>>
  description : TEXT
}

entity "users" as users {
  *id : SERIAL <<PK>>
  --
  #role_id : INT <<FK>>
  name : VARCHAR(100)
  email : VARCHAR(150) <<UNIQUE>>
  password_hash : VARCHAR(255)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "categories" as categories {
  *id : SERIAL <<PK>>
  --
  type : VARCHAR(10)
  name : VARCHAR(50)
  icon : VARCHAR(50)
}

entity "transactions" as transactions {
  *id : SERIAL <<PK>>
  --
  #user_id : INT <<FK>>
  #category_id : INT <<FK>>
  transaction_type : VARCHAR(10)
  amount : DECIMAL(15,2)
  description : TEXT
  transaction_date : DATE
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

entity "receipts" as receipts {
  *id : SERIAL <<PK>>
  --
  #transaction_id : INT <<FK>>
  object_url : VARCHAR(255)
  object_key : VARCHAR(255)
  filename : VARCHAR(150)
  file_type : VARCHAR(50)
  uploaded_at : TIMESTAMP
}

entity "audit_logs" as audit_logs {
  *id : SERIAL <<PK>>
  --
  #user_id : INT <<FK>>
  action : VARCHAR(50)
  entity : VARCHAR(50)
  entity_id : INT
  ip_address : VARCHAR(45)
  created_at : TIMESTAMP
}

' ============ RELATIONS ============

roles ||--o{ users : "1 : N"
users ||--o{ transactions : "1 : N"
users ||--o{ audit_logs : "1 : N"
categories ||--o{ transactions : "1 : N"
transactions ||--o{ receipts : "1 : N"

' ============ NOTES ============

note right of transactions
  Index: idx_transactions_user_date
  (user_id, transaction_date)
end note

note bottom of receipts
  Metadata file receipt.
  File fisik disimpan di MinIO.
end note

@enduml
